blank_issues_enabled: true
contact_links:
  - name: Discord Community
    url: https://discord.gg/k9F7SyTgqn
    about: Join our Discord server for real-time help and discussions
  - name: Contributing Guide
    url: https://github.com/zingzy/pollinations.ai-bot/blob/main/.github/contributing.md
    about: Read our contributing guidelines before submitting issues or PRs
  - name: Pollinations.ai API Documentation
    url: https://github.com/pollinations/pollinations/blob/master/APIDOCS.md
    about: Official API documentation for Pollinations.ai 